import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const HSK_DIR = path.join(__dirname, 'src', 'data', 'hsk');
const LOADER_FILE = path.join(__dirname, 'src', 'data', 'hskLoader.js');

// CDN Base for drkameleon's complete HSK dataset
const BASE_URL = 'https://raw.githubusercontent.com/drkameleon/complete-hsk-vocabulary/main/wordlists/inclusive/old/';

async function setupData() {
  console.log('🚀 Setting up native HSK datasets...\n');

  // Ensure directory exists
  if (!fs.existsSync(HSK_DIR)) {
    fs.mkdirSync(HSK_DIR, { recursive: true });
  }

  // Fetch HSK 1 to 6
  for (let lvl = 1; lvl <= 6; lvl++) {
    const url = `${BASE_URL}${lvl}.json`;
    const targetFile = path.join(HSK_DIR, `hsk${lvl}.json`);

    try {
      console.log(`📥 Downloading HSK ${lvl} data...`);
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP Error ${res.status}`);
      
      const data = await res.json();
      fs.writeFileSync(targetFile, JSON.stringify(data, null, 2));
      console.log(`✅ Saved HSK ${lvl} (${data.length} words) to src/data/hsk/hsk${lvl}.json`);
    } catch (err) {
      console.error(`❌ Failed downloading HSK ${lvl}:`, err.message);
    }
  }

  // Create src/data/hskLoader.js automatically
  console.log('\n📝 Generating src/data/hskLoader.js...');
  const loaderContent = `// Automatically generated by setup-data.js
import hsk1 from './hsk/hsk1.json';
import hsk2 from './hsk/hsk2.json';
import hsk3 from './hsk/hsk3.json';
import hsk4 from './hsk/hsk4.json';
import hsk5 from './hsk/hsk5.json';
import hsk6 from './hsk/hsk6.json';

const ALL_LEVELS = {
  '1': hsk1,
  '2': hsk2,
  '3': hsk3,
  '4': hsk4,
  '5': hsk5,
  '6': hsk6,
};

export function getNativeDeck(activeLevels = ['3']) {
  let combinedRaw = [];

  activeLevels.forEach((lvl) => {
    const list = ALL_LEVELS[lvl] || [];
    const formatted = list.map((item, idx) => {
      const char = item.hanzi || item.simplified || item.character || '字';
      const meanings = item.translations || item.meanings || [item.meaning || 'meaning'];
      const pinyinStr = item.pinyin || '';

      return {
        id: \`hsk\${lvl}_\${idx}_\${char}\`,
        character: char,
        pinyin: pinyinStr,
        meaning: Array.isArray(meanings) ? meanings.join(', ') : meanings,
        hskLevel: \`HSK \${lvl}\`,
        sentence: item.example?.hanzi || \`这是“\${char}”字。\`,
        sentencePinyin: item.example?.pinyin || '',
        sentenceEnglish: item.example?.translation || \`This is the character for \${Array.isArray(meanings) ? meanings[0] : meanings}.\`,
        culturalNote: item.radical ? \`Radical: \${item.radical}\` : 'Standard HSK vocabulary word.',
      };
    });

    combinedRaw = [...combinedRaw, ...formatted];
  });

  return combinedRaw;
}
`;

  fs.writeFileSync(LOADER_FILE, loaderContent);
  console.log('✨ Loader generated successfully!\n');
  console.log('🎉 Done! All datasets are now native inside your app.');
}

setupData();